In [1]:
import numpy as np

A = np.array([[3, 2, 2],
              [2, 3, -2]])

print("Original Matrix A:")
print(A)

U, S, VT = np.linalg.svd(A)

print("\nMatrix U:")
print(U)

print("\nSingular values (S):")
print(S)

print("\nMatrix V^T:")
print(VT)

S_matrix = np.zeros((U.shape[0], VT.shape[0]))
np.fill_diagonal(S_matrix, S)

A_reconstructed = np.dot(U, np.dot(S_matrix, VT))

print("\nReconstructed Matrix A:")
print(A_reconstructed)

is_close = np.allclose(A, A_reconstructed)
print("\nReconstruction successful:", is_close)


Original Matrix A:
[[ 3  2  2]
 [ 2  3 -2]]

Matrix U:
[[-0.70710678 -0.70710678]
 [-0.70710678  0.70710678]]

Singular values (S):
[5. 3.]

Matrix V^T:
[[-7.07106781e-01 -7.07106781e-01 -6.47932334e-17]
 [-2.35702260e-01  2.35702260e-01 -9.42809042e-01]
 [-6.66666667e-01  6.66666667e-01  3.33333333e-01]]

Reconstructed Matrix A:
[[ 3.  2.  2.]
 [ 2.  3. -2.]]

Reconstruction successful: True
